# Generated by Django 5.1.4 on 2025-01-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0003_newtable_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtable',
            old_name='auther',
            new_name='author',
        ),
    ]
