# Generated by Django 5.1.4 on 2025-01-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0004_rename_auther_newtable_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtable',
            name='image',
            field=models.ImageField(blank=True, default='a.png', upload_to='media/'),
        ),
    ]
