# Generated by Django 5.1.4 on 2025-01-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0005_alter_newtable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtable',
            name='image',
            field=models.ImageField(blank=True, default='a.png', upload_to=''),
        ),
    ]
